### ISSUE TITLE
Paclear does not show animation in VSCode terminal

### ISSUE THREAD

**Issue by andrewginns** [orangekame3/paclear#16]
Installed paclear via brew on an Ubuntu host but no animation is shown before the terminal is cleared in VSCode remote SSH terminal. paclear functions fine when called via Windows Terminal SSH'ing to the same host.

**Comment by orangekame3** [comment]
Thank you for the comment. I will check it out.

**Comment by andrewginns** [comment]
I am strangely no longer seeing the issue, it could be that I needed to re-establish the connection to VSCode before the animation functioned properly. For those who have the issue I would recommend the connection is killed, then restarted.
