### ISSUE TITLE
unable to install in windows terminal

### ISSUE THREAD

**Issue by tarekeleter** [orangekame3/paclear#17]
was unable to configure correctly to install in windows terminal

**Comment by orangekame3** [comment]
Hi, I'm sorry to hear you're experiencing issues installing our CLI on Windows Terminal.

 Could you please specify which installation method you used? We offer four methods: go install, Homebrew, downloading the binary directly, and using winget. 

Knowing the method you used will help us assist you better. Thanks!

**Comment by tarekeleter** [comment]
I Attempted to install via winget

**Comment by tarekeleter** [comment]
after attempting to run .\win-installer.sh in windows terminal it boots up Vs code and does not work :(

**Comment by orangekame3** [comment]
The winget installation method worked fine on my end, but it seems there are cases where it doesn't go smoothly. 

Do you have Go installed? If you use go install, we have confirmed that it works for others. Alternatively, you could manually download the executable file and run it directly.

**Comment by orangekame3** [comment]
The winget installation method is still relatively new with fewer use cases, so I'll conduct some additional testing on my end.

**Comment by tarekeleter** [comment]
Fixed, Just had to clear the defaults for .sh files on my system

**Comment by orangekame3** [comment]
Great to hear, I'm glad it worked out for you!
