### ISSUE TITLE
Add option to set deafult color and speed

### ISSUE THREAD

**Issue by tarekeleter** [orangekame3/paclear#18]
Can you add a setting to enable the default color and speed?

**Comment by orangekame3** [comment]
No, as of now, I do not plan to provide an option for default settings. You can likely achieve what you're looking for by setting up an alias.

For example, you can configure it as follows:

```shell
alias paclear="paclear -c yellow -s 2"
```

**Comment by horw** [comment]
I agree that using an alias works well for this type of default values.
